name: Server Image Build

on:
  push:
    branches: [ master ]
    paths:
      - 'server/*'
      - '.github/workflows/*'

defaults:
  run:
    shell: bash
    working-directory: server

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GCLOUD_KEY }}
        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: disneyparty/server
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          registry: eu.gcr.io
          workdir: server
